name: CI Pipeline

on:
  push:
    branches:
      - master
#  pull_request:
#    branches:
#      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Cache Python dependencies
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-mock responses pytest-dotenv

      # Run tests with coverage
      - name: Run tests
        env:
          SEARCH_API_KEY: test_key
          GEMINI_API_KEY: test_key
          URL: https://google.serper.dev/search
        run: |
          pytest --cov=src --cov-report=xml tests/
        continue-on-error: true

      # Upload coverage report (optional)
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
        if: success()

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ask-web .

      # Test Docker image
      - name: Test Docker image
        run: |
          docker run -d -p 8501:8501 --name ask-web-container \
            -e SEARCH_API_KEY=test_key \
            -e GEMINI_API_KEY=test_key \
            -e URL=https://google.serper.dev/search \
            ask-web
          sleep 10
          curl -f http://localhost:8501 || exit 1
          docker stop ask-web-container
          docker rm ask-web-container